[package]
name = "algorithm_m"
version = "0.1.0"
edition = "2024"

[features]
"unsafe-fast-index" = []

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "dance"
harness = false
